### PR TITLE
Add base test case and scenario to test processor

### PR DESCRIPTION
**Pull request by francescotrucchia**
Scenario to test processor

### CODE REVIEW

**Comment by francescotrucchia** [comment]
Hi guys, any chance to receive a review for this PR? Thanks

**Comment by reenl** [comment]
Please correct me if I'm wrong but the way I understood the processor was that its purpose was to do something with events, like sending e-mails or calling a webhook. Ofcourse you can inject the CommandBus but it is not requirement. For Event -> Command flow an attempt has been made to create a Saga library, but afaik it is experimental.

I'm not a maintainer so please wait for them for an official response :)

**Comment by othillo** [comment]
I agree with @reenl here. I'm not comfortable with injecting a command bus into a processor.
To me a processor is just an absolute minimal implementation of EventListener. You can do whatever you want which does mean you have to write the tests yourself.

**Comment by othillo** [comment]
Thanks, @francescotrucchia! But I don't think this should be merged. See the earlier remarks.

**Pull request closed without merging**
