### PR TITLE
apply coding standards

### PR DESCRIPTION
**Pull request by othillo**
We use Symfony coding standards since https://github.com/broadway/broadway/pull/320.
This PR applies them.

### CODE REVIEW

**Comment by msvrtan** [comment]
Hey @othillo , 

I see you are running a major code standards apply, would you consider adding this rules? 

```
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
        'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals' => true
        ],
        'ordered_imports' => true,
        'phpdoc_order' => true,
```

To explain the suggestions:

`        'array_syntax' => ['syntax' => 'short'], `
I guess since you added strict types declarations that 5.x is not supported any more so this should not be an issue as well and helps readability...

```
        'binary_operator_spaces' => [
            'align_double_arrow' => true,
            'align_equals' => true
        ],
```
I think that having equals and double arrows alligned helps the code readbility a lot IMO

`        'ordered_imports' => true,`
This would sort the imports in alphabetical order, while broadway doesnt have that much imports per file, might not be needed but not sure anyone would mind (especially OCD ppl like me might be gratefull :) )


`        'phpdoc_order' => true,`
Same thing as last one, not sure it's needed but might help with future contributors to avoid (can you please reorder the docblocks)

**Comment by othillo** [comment]
hey Miro!

you're talking to a fellow OCD person here ;)
I understand and personally like your suggestions. In fact they were part of our previous but unofficial coding standards.

The thing is: I don't want to bother contributors with coding standards, especially not when they are not standard. Which is my second point: I want them to be a simple as possible.
That's why we chose the Symfony standard (with strict types). And to enforce it on CI this PR is necessary.

**Comment by asm89** [comment]
👍

**Comment by msvrtan** [comment]
I understand completely, I was just expecting that adding those rules will not create any issues since to be up-to Symfony standard you would be running php-cs-fixer too (at least I would since I dont even try to manually guess the correct details :) )

**Pull request merged**
