### PR TITLE
In memory repository can find by value object

### PR DESCRIPTION
**Pull request by francescotrucchia**
With this patch findBy method can find also on getter method that return a value object

### CODE REVIEW

**Comment by francescotrucchia** [comment]
@othillo any update for this PR?

**Comment by wjzijderveld** [comment]
Would you mind adding a test for this? https://github.com/broadway/broadway/blob/master/test/Broadway/ReadModel/RepositoryTestCase.php

**Comment by reenl** [comment]
Not sure about this but a php object that doesn't have a __toString method would generate a catchable fatal error with this change:

```
❯ php -a
Interactive mode enabled

php > class A {}
php > $a = new A();
php > echo (string) $a;
PHP Catchable fatal error:  Object of class A could not be converted to string in php shell code on line 1
PHP Stack trace:
PHP   1. {main}() php shell code:0
```

**Comment by francescotrucchia** [comment]
@reenl I fix the behaviour. 
@wjzijderveld I add the test.
Thanks for feedback

**Comment by francescotrucchia** [comment]
Hi guys, any update for this PR? Thanks

**Comment by othillo** [comment]
@francescotrucchia can you rebase this, please?

**Pull request closed without merging**
